[hub]
hub ansible_host=10.10.10.10 ansible_user=admin ansible_password=changeme ansible_network_os=fortinet.fortios.fortios

[branches]
branch1 ansible_host=10.10.11.10 ansible_user=admin ansible_password=changeme ansible_network_os=fortinet.fortios.fortios
branch2 ansible_host=10.10.12.10 ansible_user=admin ansible_password=changeme ansible_network_os=fortinet.fortios.fortios

[sase]
fortisase_pop ansible_host=100.64.0.10 ansible_user=apiuser ansible_password=changeme ansible_network_os=fortinet.fortisase.fortisase

[iam]
iam ansible_host=192.168.100.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
